android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx384m -XX:MaxMetaspaceSize=320m -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
